sudo: required
services: 
  - docker

before_install:
  - docker build -t rohitaror/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rohitaror/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app:  "docker-react-app"
  env:  "DockerReactApp-env"
  bucket_name:  "elasticbeanstalk-us-west-2-985408864052"
  bucket_path:  "docker-react-app"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY" 